# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: config
      run: git config pull.rebase true
    
    - name: name
      run: git config --global user.name 'gitcommit-at-506370942921'
      
    - name: pass
      run: git config --global credential.helper "!aws codecommit --profile CODECOMMIT credential-helper $@"'
    - name: http
      run: git config --global credential.UseHttpPath true


    # Runs a single command using the runners shell
    - name: remote
      run: git remote add codecommit "ssh://git-codecommit.us-west-2.amazonaws.com/v1/repos/my-git"
    
    - name: remote2
      run: git remote add master "https://github.com/mi-ki-ri/git-from-codecommit.git"

    # Runs a set of commands using the runners shell
    - name: pull
      run: git pull codecommit master
      
    - name: push
      run: git push origin master
